name = "Carlo"
uuid = "780c37f4-4e5a-43de-9e79-65c261e525a4"
authors = ["Lukas Weber"]
version = "0.2.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgParse = "1.1.4"
Dates = "1.7"
ElasticArrays = "1.2.11"
HDF5 = "0.17.1"
JSON = "0.21.4"
Logging = "1.7"
MPI = "0.20.16"
MPIPreferences = "0.1.9"
Measurements = "2.10.0"
PrecompileTools = "1.2.0"
PrettyTables = "2.2.7"
Printf = "1.7"
Random = "1.7"
Serialization = "1.7"
Statistics = "1.7"
StructEquality = "2.1.0"
Test = "1.7"
julia = "1.7"

[extras]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "StructEquality", "Serialization"]
